Repository FRONTENDBOOTCAMP-13th/love-and-freedom, pull requests merged in 2025-03, with the labels that each got.

#10 기본 폴더 구조 세팅
  public/fonts/dummy.md
  public/icons/dummy.md
  public/images/dummy.md
  src/components/dummy.md
  src/pages/dummy.md
Labels: :pencil2: Rename

#20 :sparkles: feat: 헤더 추가
  public/images/header/header-logo-pc.png
  public/images/header/header-logo.png
  public/images/header/header-naver-icon.png
  public/images/header/search-icon-pc.png
  public/images/header/search-icon.png
  public/images/header/xxx.svg
  src/components/header/component-header.css
  src/components/header/component-header.html
  src/style.css
  vite.config.js
Labels: :sparkles: Feature

#28 ✨ feat:딱지, 딱지 필터 구현
  index.html
  public/images/atlas/sp_common.png
  public/images/atlas/sp_pc_common.png
  public/images/ttakji/ttakji-audio/ttakji-audio.jpg
  public/images/ttakji/ttakji-category/category-jaeneungtv.jpg
  public/images/ttakji/ttakji-character/ttakji-character.png
  src/components/ttakji-category/ttakji-category.css
  src/components/ttakji-category/ttakji-category.html
  src/components/ttakji-filter/ttakji-filter.css
  src/components/ttakji-filter/ttakji-filter.html
  src/components/ttakji/ttakji.css
  src/components/ttakji/ttakji.html
  src/style.css
  vite.config.js
Labels: :sparkles: Feature

#33 폰트 관련 버그 수정 & 기타 수정
  index.html
  public/fonts/nanumsquareround.css
  public/fonts/naver.css
  public/fonts/woff2/nanumsquareround.css
  public/fonts/woff2/naver.css
  src/style.css
Labels: :bug: BugFix

#45 ✨ feat: 공지 모달 구현
  index.html
  src/components/notice-modal/notice-modal.css
  src/components/notice-modal/notice-modal.html
  src/style.css
Labels: :sparkles: Feature

#47 :bug: fix: 83번 빠진 괄호 추가
  index.html
Labels: :bug: BugFix

#63 :sparkles: feat: 인기캐릭터, 오디오동요동화, 추천캐릭터, 캐릭터페이지 레이아웃 구현
  index.html
  src/components/layout/layout-ttakji/layout-ttakji.css
  src/components/layout/layout-ttakji/layout-ttakji.html
  src/components/ttakji-filter/ttakji-filter.css
  src/components/ttakji/ttakji.css
  src/style.css
Labels: :sparkles: Feature, :recycle: refactor

#81 :sparkles: feat:banner-layout완성
  src/components/banner-layout/banner-layout.css
  src/components/banner-layout/banner-layout.html
Labels: :sparkles: Feature

#82 :eye: accessibility: 탑 버튼 웹 접근성 작업
  src/components/top-link/top-link.html
Labels: :eye: Accessibility

#84 :eye: accessibility: 헤더 웹 접근성 작업
  src/components/header/header.html
Labels: :eye: Accessibility

#83 :recycle: refactor:카테고리 딱지 반응형 수정
  src/components/ttakji-category/ttakji-category.css
  src/components/ttakji-category/ttakji-category.html
Labels: :recycle: refactor

#92 :eye: accessibility: 딱지, 필터 접근성 향상 작업
  src/components/layout/layout-ttakji/layout-ttakji.html
  src/components/ttakji-filter/ttakji-filter.css
  src/components/ttakji-filter/ttakji-filter.html
  src/components/ttakji/ttakji.css
  src/components/ttakji/ttakji.html
Labels: :eye: Accessibility

#104 캐릭터 페이지 구현
  public/images/page-images/character/bg-img-character-page.png
  src/components/banner-layout/banner-layout.css
  src/components/layout/layout-ttakji/layout-ttakji.css
  src/components/ttakji-filter/ttakji-filter.css
  src/pages/character/character.css
  src/pages/character/character.html
Labels: :sparkles: Feature, :recycle: refactor

#105 :bug: fix: main 태그 선택자 오류 수정
  src/pages/character/character.css
  src/pages/character/character.html
Labels: :bug: BugFix

#122 공지 모달 홈 페이지에 적용
  public/images/modal/top-modal.png
  src/components/test-index/test-index.css
  src/components/test-index/test-index.html
  src/pages/home/home.html
Labels: :sparkles: Feature

#124 Docs/readme
  README.md
Labels: :memo: Documentation

#125 Feature/animation position
  src/components/animation/animation.css
  src/components/base-layout/base-layout.css
  src/pages/category/category.html
  src/pages/home/home.html
Labels: :sparkles: Feature

#127 :sparkles: feat: 홈 페이지에 링크카드 추가
  src/components/linkcard/linkcard.css
  src/components/linkcard/linkcard.html
  src/pages/home/home.css
  src/pages/home/home.html
Labels: :sparkles: Feature

#128 :memo: docs: Update README.md
  README.md
Labels: :memo: Documentation

#131 캐릭터페이지 찜 버튼 적용 및 애니메이션 재생 버그 수정
  src/components/ttakji/ttakji.html
  src/pages/character/character.css
  src/pages/character/character.html
  src/zzim.js
Labels: :bug: BugFix, :recycle: refactor

#133 Bug/like page animaition
  README.md
  src/components/banner-layout/banner-layout.css
  src/components/banner-layout/banner-layout.html
  src/components/linkcard/linkcard.html
  src/pages/character/character.css
  src/pages/like/likepage.html
Labels: :bug: BugFix

#130 Remove/anycode
  src/components/base-layout/base-layout.css
  src/components/base-layout/base-layout.html
  src/components/category-button/category-button.html
  src/components/header/header.css
  src/components/header/header.html
  src/pages/category/category.html
  src/pages/character/character.html
  src/pages/home/home.html
  src/pages/like/likepage.css
  src/pages/like/likepage.html
Labels: :bug: BugFix, :lion: chore

#136 :eye: accessibility: index h1 접근성 수정
  src/components/test-index/test-index.html
Labels: :eye: Accessibility

#139 html error 및 접근성 오류 수정 - 딱지, 딱지필터, 캐릭터 페이지
  src/components/ttakji-filter/ttakji-filter.html
  src/components/ttakji/ttakji.html
  src/pages/character/character.html
Labels: :bug: BugFix, :eye: Accessibility

#142 Bugfix/category page
  src/components/square-ttakji-layout/square-layout.css
  src/pages/category/category.html
  src/pages/like/likepage.html
Labels: :bug: BugFix, :eye: Accessibility

#141 :eye: accessibility: 홈 페이지 품질 작업
  src/components/header/header.html
  src/pages/home/home.html
Labels: :bug: BugFix, :eye: Accessibility

#143 :bug: fix: character.css, readme.md 정상화
  README.md
  src/pages/character/character.css
Labels: :bug: BugFix
